### ISSUE TITLE
feat: Fetch updates from repository

### ISSUE THREAD

**Issue by annaekli** [dd2480-2019-group13/kth-dd2480-assignment2#6]
* implement fetchRepoUpdates() in CIWorker.java
* providing the functionality of step 3) in the Outline architecture of [CI server](https://trello-attachments.s3.amazonaws.com/5c4ee33443b25f6db0785109/5c532662e8ae4879f533081b/1a6e9e57a34aca6732202929f0f17801/image.png)

**Comment by annaekli** [comment]
[Trello](https://trello.com/c/L8tQW9vN)

**Comment by lilfelix** [comment]
@fredrikfloven I know you've been checking out using JGit, so we might no need anything else.
Just wanted to share this gradle-git plugin that I found. Looks pretty cool:
https://github.com/ajoberstar/grgit
